### ISSUE TITLE
README.rst is missing when installing the package

### ISSUE THREAD

**Issue by arnematzen** [eurostat/happyGISCO#2]
Can README.rst be added to avoid this error?

--

ERROR: Command errored out with exit status 1:
     command: /opt/hostedtoolcache/Python/3.8.5/x64/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-m3yy8ww3/package-two/setup.py'"'"'; __file__='"'"'/tmp/pip-install-m3yy8ww3/package-two/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-yv41yu8d
         cwd: /tmp/pip-install-m3yy8ww3/package-two/
    Complete output (7 lines):
    /tmp/pip-install-m3yy8ww3/package-two/setup.py:24: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
      import os, imp
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-m3yy8ww3/package-two/setup.py", line 147, in <module>
        long_description = open(os.path.join(os.path.dirname(__file__),'README.rst'), encoding='utf-8').read(),
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-m3yy8ww3/package-two/README.rst'

**Comment by mmoraschini** [comment]
Same problem here...
